export const ALLOWED_ICONS = [
  { title: 'Trofeo / Premio', value: 'Award' },
  { title: 'Graduación', value: 'GraduationCap' },
  { title: 'Grupo de personas', value: 'Users' },
  { title: 'Paleta de colores', value: 'Palette' },
  { title: 'Avión', value: 'Plane' },
  { title: 'Globo terráqueo', value: 'Globe' },
  { title: 'Oído / Escucha', value: 'Ear' },
  { title: 'Corazón', value: 'Heart' },
  { title: 'Escudo / Protección', value: 'Shield' },
  { title: 'Escudo con check', value: 'ShieldCheck' },
  { title: 'Destellos', value: 'Sparkles' },
  { title: 'Burbuja de chat', value: 'MessageCircle' },
  { title: 'Brújula', value: 'Compass' },
  { title: 'Reloj', value: 'Clock' },
  { title: 'Sobre de correo', value: 'Mail' },
  { title: 'Teléfono', value: 'Phone' },
  { title: 'Descarga', value: 'Download' },
  { title: 'Libro abierto', value: 'BookOpen' },
  { title: 'Cerebro', value: 'Brain' },
  { title: 'Bombilla', value: 'Lightbulb' },
  { title: 'Diana / Objetivo', value: 'Target' },
  { title: 'Apretón de manos', value: 'Handshake' },
  { title: 'Árbol / Crecimiento', value: 'TreePine' },
  { title: 'Sol / Bienestar', value: 'Sun' },
  { title: 'Estrella', value: 'Star' },
  { title: 'Candado', value: 'Lock' },
  { title: 'Cara sonriente', value: 'Smile' },
  { title: 'Círculo con check', value: 'CircleCheck' },
  { title: 'Regalo', value: 'Gift' },
  { title: 'Calendario', value: 'Calendar' },
] as const

export type AllowedIcon = (typeof ALLOWED_ICONS)[number]['value']
